# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: middagsasen-planner-API PR

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'src/Middagsasen.Planner.Api/**/*'
      - 'src/Middagsasen.Planner.Api.Tests/**'
      - 'src/Middagsasen.Planner.Database/**'
      - 'Directory.Packages.props'
      - 'global.json'
      - '.github/workflows/pr_middagsasen-planner.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test with dotnet
        run: dotnet test src/Middagsasen.Planner.Api.Tests/Middagsasen.Planner.Api.Tests.csproj --configuration Release --no-build

      - name: dotnet publish
        run: dotnet publish src/Middagsasen.Planner.Api/Middagsasen.Planner.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
